config/routes.rb
Greenway::Application.routes.draw do
  resources :clientmails
  devise_for :users
  resources :activites
  root 'pages#accueil'

end

app/models/activite.rb
class Activite < ActiveRecord::Base

 geocoded_by :adresse
 after_validation :geocode
 
end

app/models/clientmail.rb
class Clientmail < ActiveRecord::Base

	  validates :mail, presence: true, uniqueness: true
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activites_controller.rb
class ActivitesController < ApplicationController
  before_action :set_activite, only: [:show, :edit, :update, :destroy]

  # GET /activites
  # GET /activites.json
  def index
    @activites = Activite.all
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end

  # GET /activites/1
  # GET /activites/1.json
  def show
  end

  # GET /activites/new
  def new
    @activite = Activite.new
  end

  # GET /activites/1/edit
  def edit
  end

  # POST /activites
  # POST /activites.json
  def create
    @activite = Activite.new(activite_params)

    respond_to do |format|
      if @activite.save
        format.html { redirect_to @activite, notice: 'Activite was successfully created.' }
        format.json { render action: 'show', status: :created, location: @activite }
      else
        format.html { render action: 'new' }
        format.json { render json: @activite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activites/1
  # PATCH/PUT /activites/1.json
  def update
    respond_to do |format|
      if @activite.update(activite_params)
        format.html { redirect_to @activite, notice: 'Activite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activites/1
  # DELETE /activites/1.json
  def destroy
    @activite.destroy
    respond_to do |format|
      format.html { redirect_to activites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activite
      @activite = Activite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activite_params
      params.require(:activite).permit(:titre, :description, :typeactivite, :prix, :pays, :adresse, :datedebut, :datefin)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientmails_controller.rb
class ClientmailsController < ApplicationController
  before_action :set_clientmail, only: [:show, :edit, :update, :destroy]


  def index
    @clientmails = Clientmail.all
  end

  def show
  end

  def new
    @clientmail = Clientmail.new
  end

  # GET /clientmails/1/edit
  def edit
  end

  def create
    @clientmail = Clientmail.new(clientmail_params)

    respond_to do |format|
      if @clientmail.save
        format.html { redirect_to "http://localhost:3000", notice: 'Votre mail a bien été enregistré.' }
        format.json { redirect_to "http://localhost:3000", status: :created, location: @clientmail }
      else
        format.html { redirect_to "http://localhost:3000", notice: 'Ce mail existe déjà ou il est invalide.'  }
        format.json { render json: @clientmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientmails/1
  # PATCH/PUT /clientmails/1.json
  def update
    respond_to do |format|
      if @clientmail.update(clientmail_params)
        format.html { redirect_to @clientmail, notice: 'Clientmail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @clientmail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientmails/1
  # DELETE /clientmails/1.json
  def destroy
    @clientmail.destroy
    respond_to do |format|
      format.html { redirect_to clientmails_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clientmail
      @clientmail = Clientmail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clientmail_params
      params.require(:clientmail).permit(:mail)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def accueil
	
	end


	def contact

	end

	def faq
		
	end

	def activites
		
	end

end

app/helpers/activites_helper.rb
module ActivitesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientmails_helper.rb
module ClientmailsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/activites/_form.html.erb
<%= form_for(@activite) do |f| %>
  <% if @activite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activite.errors.count, "error") %> Activité non sauvegardée:</h2>

      <ul>
      <% @activite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit 'Créer', class: 'button small round success', style: 'color:#fff; float:right;  margin-top:15px; margin-left:10px;'%>
    <%= link_to 'Retour', activites_path, class: "button small round success", style: "float:right; margin-top:15px;" %>
  </div>
<div class="row" style="clear: both;">
  <div class="large-6 small-12 columns">
  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :titre %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label "Type d'activité" %><br>
    <%= f.text_field :typeactivite %>
  </div>
  <div class="field">
    <%= f.label :prix %><br>
    <%= f.text_field :prix %>
  </div>
  </div>
  <div class="large-6 small-12 columns">
  <div class="field">
  <div class="field">
    <%= f.label :pays %><br>
    <%= f.text_field :pays %>
  </div>
  <div class="field">
    <%= f.label :adresse %><br>
    <%= f.text_field :adresse %>
  </div>
  <div class="field">
    <%= f.label "Date de debut (jj/mm/aa)" %><br>
    <%= f.date_field :datedebut %>
  </div>
  <div class="field">
    <%= f.label "Date de fin (jj/mm/aa)" %><br>
    <%= f.date_field :datefin %>
  </div>
  </div>

</div>
<% end %>

app/views/activites/edit.html.erb
<br/><br/><br/>
<div class="row">
<h1>Editing activite</h1>

<%= render 'form' %>

<%= link_to 'Show', @activite %> |
<%= link_to 'Back', activites_path %>
</div>

app/views/activites/index.html.erb
<br/><br/><br/>
<div class="row">

<h1>Listing activites</h1>
<%= link_to 'Nouvelle Activité', new_activite_path, class: 'button small success round', style:"float:right;" %>

<div style="clear:both;">
<table>
  <thead>
    <tr>
      <th>Titre</th>
      <th>Description</th>
      <th>Typeactivite</th>
      <th>Prix</th>
      <th>Pays</th>
      <th>Adresse</th>
      <th>Datedebut</th>
      <th>Datefin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @activites.each do |activite| %>
      <tr>
        <td><%= activite.titre %></td>
        <td><%= activite.description %></td>
        <td><%= activite.typeactivite %></td>
        <td><%= activite.prix %></td>
        <td><%= activite.pays %></td>
        <td><%= activite.adresse %></td>
        <td><%= activite.datedebut %></td>
        <td><%= activite.datefin %></td>
        <td><%= link_to 'Voir', activite %></td>
        <td><%= link_to 'Editer', edit_activite_path(activite) %></td>
        <td><%= link_to 'Supprimer', activite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

</div>

app/views/activites/new.html.erb
<br/><br/><br/>
<div class="row">
<h1>Nouvelle Activité</h1>


<%= render 'form' %>

</div>

app/views/activites/show.html.erb
<br/><br/><br/>
<div  class="row">
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="small-12 large-6 columns">
    <h1><%= @activite.titre %></h1>

        <p>
          <strong>Description:</strong>
          <%= @activite.description %>
        </p>

        <p>
          <strong>Typeactivite:</strong>
          <%= @activite.typeactivite %>
        </p>

        <p>
          <strong>Prix:</strong>
          <%= @activite.prix %>
        </p>


          <strong>Datedebut:</strong>
          <%= @activite.datedebut %>
        </p>

        <p>
          <strong>Datefin:</strong>
          <%= @activite.datefin %>
        </p>


        <p>
          <strong>Adresse:</strong>
          <%= @activite.adresse %>
        </p>
  </div>

  <div class="small-12 large-6 columns">
    <div style='width: 800px;'>
    <div id="map" style='width: 400px; height: 440px;'></div>
    </div>
  </div>


</div>
  

<p>

<%= link_to 'Edit', edit_activite_path(@activite) %> |
<%= link_to 'Back', activites_path %>
</div>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


 
<script type="text/javascript">
$(document).ready(function(){
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": <%= @activite.latitude %>,
      "lng": <%= @activite.longitude %>,
      "picture": {
        "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
        "width":  36,
        "height": 36,
      "infowindow": "hello!"
      },
    }
  ]);
  var mapOptions = {
  "zoom": 40,
  };
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
});
</script> 

app/views/clientmails/_form.html.erb
<%= form_for(@clientmail) do |f| %>
  <% if @clientmail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clientmail.errors.count, "error") %> prohibited this clientmail from being saved:</h2>

      <ul>
      <% @clientmail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientmails/edit.html.erb
<h1>Editing clientmail</h1>

<%= render 'form' %>

<%= link_to 'Show', @clientmail %> |
<%= link_to 'Back', clientmails_path %>

app/views/clientmails/index.html.erb
<div class="row">
<h1>Listing clientmails</h1>

<table>
  <thead>
    <tr>
      <th>Mail</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clientmails.each do |clientmail| %>
      <tr>
        <td><%= clientmail.mail %></td>
        <td><%= link_to 'Edit', edit_clientmail_path(clientmail), class:"button small rounded alert" %></td>
        <td><%= link_to 'Destroy', clientmail, method: :delete, class:"button small rounded alert" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/clientmails/mailerror.html.erb
<%= render'layouts/diapo/accueil' %>
<div class="accueil-rubriques">


	<div class="row">


	
		<div class=" rubrique small-12 large-4 columns">
			<h2>Plein air</h2>	
			<%= image_tag "icons/air.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Aquatique</h2>
			<%= image_tag "icons/wave.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Nourriture</h2>
			<%= image_tag "icons/food.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Excursions</h2>
			<%= image_tag "icons/walk.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Glisse</h2>
			<%= image_tag "icons/snow.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Insolite</h2>
			<%= image_tag "icons/chalet.png" %>
		</div>
	</div>

</div>

app/views/clientmails/mailsuccess.html.erb
<%= render'layouts/diapo/accueil' %>
<div class="accueil-rubriques">

	<div class="row">



	</div>
	
	<div class="row">
		<div class=" rubrique small-12 large-4 columns">
			<h2>Plein air</h2>	
			<%= image_tag "icons/air.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Aquatique</h2>
			<%= image_tag "icons/wave.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Nourriture</h2>
			<%= image_tag "icons/food.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Excursions</h2>
			<%= image_tag "icons/walk.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Glisse</h2>
			<%= image_tag "icons/snow.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Insolite</h2>
			<%= image_tag "icons/chalet.png" %>
		</div>
	</div>

</div>

app/views/clientmails/new.html.erb
<h1>New clientmail</h1>

<%= render 'form' %>

<%= link_to 'Back', clientmails_path %>

app/views/clientmails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mail:</strong>
  <%= @clientmail.mail %>
</p>

<%= link_to 'Edit', edit_clientmail_path(@clientmail) %> |
<%= link_to 'Back', clientmails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "PLAY IT GREEN" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render'layouts/menus/principal' %>
    <div><br/>    
            <%= javascript_include_tag "application" %> 

        <%= yield %>
    </div>


  </body>

</html>

app/views/layouts/diapo/_accueil.erb
<div class="diapo-container">
		<div class="diapo-search">
			<div class="row">
				<div class="small-12">
					<%= image_tag "icons/world.png" %>
					<h1 style="color:white;">PLAY IT GREEN</h1>
	        		<h2 style="color:white;">Jouez la Green, où que vous soyiez </h2>
	        		
				</div>
			</div>       		
     	<div class="row collapse">
			<div class="small-12 columns">
				<% @clientmail = Clientmail.new %>
				<%= form_for @clientmail do |f| %>
							<% if @clientmail.errors.any? %>
							    <div id="error_explanation">
							      <h2><%= pluralize(@clientmail.errors.count, "error") %> prohibited this clientmail from being saved:</h2>
							      <ul>
							      <% @clientmail.errors.full_messages.each do |msg| %>
							        <li><%= msg %></li>
							      <% end %>
							      </ul>
							    </div>
							  <% end %>
				
				<div class="row collapse">
				<div class="small-10 columns ">
				<%= f.text_field :mail, placeholder: "mon@mail.com" %>
				</div>
				<div class="small-2 columns"><%= f.submit "Envoyer", class:"button postfix"%></div>
				</div>
				<h3 style="color:white;">Rester informé sur nos activiteés nature</h3>
			</div>

				<% end %>
		</div>	
		
  <p ><%= notice %></p>  


  <p ><%= alert %></p> 		
		</div>


</div>

app/views/layouts/menus/_principal.html.erb
<div class="contain-to-grid fixed">
<nav class="top-bar" data-topbar> 
	<ul class="title-area"> 
		<li class="name"> <h1><%= link_to "Play It Green", root_url %></h1> </li> 
	</ul> 
	<section class="top-bar-section">
		<ul class="right"> 
			<li class="active"><%= link_to "Publiez votre annonce", new_activite_path %> 
		        
      		</li>
			
		</ul>
		<ul class="left"> 
			<% if user_signed_in? %>  
			<li class="has-form">
			  <div class="row collapse">
			    <div class="small-12 columns">
			      <input type="text" placeholder="Destination">
			    </div>
			  </div>
			</li>
			<li><%= link_to "Activités" , activites_path %></li>
			<li><a href="#">Newsletter</a></li> 
			<li><a href="#">Aide</a></li> 
			
			<li><%= link_to('Déconnexion', destroy_user_session_path, :method => :delete) %></li>
			<% else %>
			  <li><%= link_to('Connexion', new_user_session_path)  %></li>
			<% end %>
			
		</ul> 
	</section> 
</nav>
</div>

app/views/pages/accueil.html.erb
<%= render'layouts/diapo/accueil' %>
<div>
	
	<div class="row">
		<div class=" rubrique small-12 large-4 columns">
			<h2>Plein air</h2>	
			<%= image_tag "icons/air.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Aquatique</h2>
			<%= image_tag "icons/wave.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Nourriture</h2>
			<%= image_tag "icons/food.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Excursions</h2>
			<%= image_tag "icons/walk.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Glisse</h2>
			<%= image_tag "icons/snow.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Insolite</h2>
			<%= image_tag "icons/chalet.png" %>
		</div>
	</div>

</div>

app/views/pages/mailsuccess.html.erb
<%= render'layouts/diapo/accueil' %>
<div class="accueil-rubriques">


	<div class="row">

	
		<div class=" rubrique small-12 large-4 columns">
			<h2>Plein air</h2>	
			<%= image_tag "icons/air.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Aquatique</h2>
			<%= image_tag "icons/wave.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Nourriture</h2>
			<%= image_tag "icons/food.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Excursions</h2>
			<%= image_tag "icons/walk.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Glisse</h2>
			<%= image_tag "icons/snow.png" %>
		</div>
		<div class="rubrique small-12 large-4 columns">
			<h2>Insolite</h2>
			<%= image_tag "icons/chalet.png" %>
		</div>
	</div>

</div>